### ISSUE TITLE
sundial.systemTheme causes lag when VSCode is opened from iTerm

### ISSUE THREAD

**Issue by sloria** [muuvmuuv/vscode-sundial#37] opened 2019-06-10 12:50 UTC
**Describe the bug**

When `"sundial.systemTheme" is enabled, there is a noticeable lag when switching between editors.

**To Reproduce**

1. Open VSCode from iTerm2 (i.e. using `code .`)
1. Set `"sundial.systemTheme: true"` in settings
1. Create a new split (`cmd+\`).
1.  Quickly switch focus repeatedly using "cmd+1" and "cmd+2"

**Expected behavior**

No noticeable lag.

**Desktop (please complete the following information):**

- OS: [e.g. macOS 10.14.5]
- VS Code [e.g. 1.3.5]
- iTerm2 Build 3.3.20190124-nightly

**Comment by sloria** [comment] 2019-06-10 13:16
I also noticed a lag when typing in iTerm. Appears to be that the system call here https://github.com/muuvmuuv/vscode-sundial/blob/3205109365bf4488d4442d718f69e55f08bb64f4/src/sensors/system-theme.ts#L7 is blocks a number of things.

**Comment by muuvmuuv** [comment] 2019-06-10 16:58
Seems this happens because node-jxa is synchronous. I will try to use another approach or lib to handle this.

Thanks for the report! Might not be fix this week but I will put it on my schedule.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sloria** [comment] 2019-06-10 17:06
Great! No rush on my end. I just switched to using `sundial.sunset` which is good enough for me.

**Comment by muuvmuuv** [comment] 2019-06-14 14:12
OK, no I was wrong, it is asynchronous so it should not block anything. 
Can you try to disable all other plugins and try it again? I can not reproduce it on my end. And could you send your VS Code sundial settings. Maybe it is a problem with the configuration.

**Comment by sloria** [comment] 2019-06-15 15:26
I tried again with all extensions except sundial enabled and there's still the lag. Here are my sundial settings:

```
  "sundial.dayTheme": "Light Delight",
  "sundial.nightTheme": "Night Owl (No Italics)",
  "sundial.systemTheme": true,
```

**Comment by muuvmuuv** [comment] 2019-06-17 08:33
I made an update, can you check if this works better now? I really have no idea where this is coming from. 

Does this occur after a VS Code restart or only when you have toggled the dark-mode already? I noticed a lag once, after I toggled it on my machine but it disappeared after I closed one file. Did you gave or rejected any macOS settings to VS Code or have other things running in background (docker, adobe CC, ...)?

**Comment by sloria** [comment] 2019-06-17 13:19
The latest update seems to have fixed the issue! 🎉

**Comment by sloria** [comment] 2019-06-18 13:46
Hm, this started happening again after restarting my computer. I'm not sure what conditions are producing the lag. I gave VSCode access to system events.

**Comment by muuvmuuv** [comment] 2019-06-19 07:25
Can you try quitting all other applications except VSCode and try it again? It is a really strange behaviour. I wonder if someone else experiences the same because I have no laggs so it may depend on your setup or some macOS specific configuration. I will ask a friend if he can test it on his machine as well to see if it happens somewhere else too.

**Comment by sloria** [comment] 2019-06-19 12:10
Aha, the issue only appears when VSCode is opened through iTerm2 using the `code` command. The lag doesn't occur when opening through Terminal.app. I've updated the issue title and description accordingly.

I'm unsure where the source of this bug is. Let me know if there's anything I can do to help diagnose the issue. If you don't think this is relevant to this project, go ahead and close it.

**Comment by muuvmuuv** [comment] 2019-06-24 06:34
I'm sorry but I can still not reproduce it. Do you have any zsh-plugins installed within iTerm2? Maybe it's a setting in iTerm which blocks this system event? Seems an iTerm problem tho. Is zsh running in your Terminal.app too?

**Comment by sloria** [comment] 2019-06-25 12:38
Yeah, I'm using [prezto](https://github.com/sorin-ionescu/prezto) running in both iTerm2 and Terminal.app.

**Comment by muuvmuuv** [comment] 2019-07-16 06:47
Hey @sloria, sorry for the late response I had plenty to do.

I have now installed Prezto and tried it again but can still not see any laggs. Could you try to `code .` with a default shell (not zsh and no plugins, just the macOS default terminal) and see if it is still causing laggs? If not, it might be a prezto plugin so try to disable all and test it again.

**Comment by muuvmuuv** [comment] 2019-09-23 16:59
I'm closing this. If the error still occurs feel free to reopen

**Closed by muuvmuuv** 2019-09-23 16:59 UTC

**Comment by sloria** [comment] 2019-09-23 18:14
OK, for now I'm just using `"sundial.sunset"`--it's closer to what I want anyway.
